import HomePage from '@/components/pages/HomePage'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Bate.io | Home",
  description: "Generated by create next app",
};

export default function HomePageWrapper() {
  return <HomePage />
}
