import LoginPage from '@/components/pages/LoginPage';
import { Metadata } from 'next';
import React from 'react';

export const metadata: Metadata = {
    title: "Bate.io  | Log In",
    description: "Generated by create next app",
};

export default function LogInPageWrapper() {
    return <LoginPage />
}
