import PasswordResetPage from '@/components/pages/PasswordResetPage'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Bate.io | Reset Password",
    description: "Generated by create next app",
};

export default function ForgotPasswordPageWrapper() {
    return <PasswordResetPage />
}
