import UpdatePasswordPage from '@/components/pages/UpdatePasswordPage'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Bate.io | Update Password",
    description: "Generated by create next app",
};

export default function UpdatePasswordPageWrapper() {
    return <UpdatePasswordPage />
}
