import type { Metadata } from "next";
import "./globals.css";
import { montserrat400 } from "@/fonts/montserrat400";

export const metadata: Metadata = {
  title: "Debate MVP",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${montserrat400.className} min-h-screen relative antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
