import MeetingPage from '@/components/pages/MeetingPage'
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Bate.io",
    description: "Generated by create next app",
};

export default function MeetingPageWrapper() {
    return <MeetingPage />
}
