import AuthWatcher from '@/components/auth/authWatcher';
import "../globals.css";
import { manrope400 } from '@/fonts/manrope400';
import { Metadata } from 'next';
import React from 'react'


export const metadata: Metadata = {
    title: "Debate MVP | Home",
    description: "Generated by create next app",
};

export default function ProtectedLayoutPage({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return <html lang="en" suppressHydrationWarning>
        <body
            className={`${manrope400.className} min-h-screen relative antialiased`}>
            <AuthWatcher />
            {children}
        </body>
    </html>

}
